# Generated by Django 4.2.7 on 2023-12-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_groupe_active_groupe_category_groupe_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descritpion', models.CharField(max_length=1000)),
                ('page', models.URLField(blank=True, null=True)),
                ('groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.groupe')),
            ],
        ),
    ]
