# Generated by Django 4.2.7 on 2023-12-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='formateur',
            field=models.CharField(default='Bernard', max_length=100),
            preserve_default=False,
        ),
    ]
